
server:
  port: 12345

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/db_employment?useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: 420130zxc
    url: ${CK_MYSQL_URL}
#    url: jdbc:mysql://127.0.0.1:3306/db_employment?useSSL=false&serverTimezone=GMT%2B8
    username: ${CK_MYSQL_USERNAME}
#    username: root
    password: ${CK_MYSQL_PASSWORD}
#    password: CaiKe@227
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 180000
      maximum-pool-size: 20
      idle-timeout: 60000
      minimum-idle: 5
      connection-timeout: 20000

logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
