server:
  port: 80

mybatis-plus:
  mapper-locations: classpath*:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  jwt:
    key: ${TOKEN_KEY}
    refresh-key: ${REFRESH_TOKEN_KEY}